//1 Import Area 


//2. defination  area 

export async function POST(){

    return Response.json({
        "results": {
            "columns": [
                "docid",
                "name",
                "distance",
                "NewAddress",
                "lat",
                "lon",
                "paidStatus",
                "compRating",
                "verified",
                "rateThis",
                "mappointer",
                "opstring",
                "area",
                "opennow",
                "type",
                "VNumber",
                "totalReviews",
                "video",
                "city",
                "thumbnail",
                "totJdReviews",
                "favflag",
                "attr_data",
                "an",
                "shopfront",
                "ishotel",
                "vertical",
                "vertical_name",
                "discount_Offer",
                "vertical_data",
                "position_flag",
                "Jadoopic",
                "sharedt_url",
                "cancall",
                "wpnumber",
                "action_node",
                "idxno",
                "linefive",
                "newadd",
                "newaddcolor",
                "dimages",
                "viewchange",
                "photocnt",
                "pdg",
                "nameln",
                "NewAddressln",
                "address_flg",
                "ask_mobile",
                "hcatarr",
                "callalocation",
                "compRatingln",
                "catalog_flag",
                "jdpay",
                "ratecard",
                "ds",
                "inapp",
                "bd_params",
                "jtkr",
                "useshare",
                "weburl",
                "rev",
                "nwtaglin",
                "tag",
                "starhotel",
                "revarr",
                "offertag",
                "ratingtag",
                "resp_rate",
                "pincode",
                "guarantee",
                "event_data",
                "msg_pop",
                "scd"
            ],
            "data": [
                [
                    "022PXX22.XX22.140524123935.V2L7",
                    "S P Art Hub",
                    "",
                    "Near Sai Baba Mandir Kharghar",
                    "19.044946666667",
                    "73.065803527778",
                    "6",
                    "4.7",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 8:00 pm</span>",
                        "timing": "10:00 am - 8:00 pm"
                    },
                    "Sector 12 Kharghar",
                    1,
                    "Drawing Classes, Painting Classes",
                    "09845259424",
                    "99",
                    "",
                    "Mumbai",
                    "https://content.jdmagicbox.com/comp/navi-mumbai/l7/022pxx22.xx22.140524123935.v2l7/catalogue/the-art-hub-kharghar-navi-mumbai-drawing-classes-nnhu5-250.jpg",
                    "99",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">9 Years in Business</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "1",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.140524123935.V2L7.jpg",
                    "https://www.justdial.com/DT-43SFBJYM",
                    1,
                    [],
                    "",
                    1,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/navi-mumbai/l7/022pxx22.xx22.140524123935.v2l7/catalogue/the-art-hub-kharghar-navi-mumbai-drawing-classes-nnhu5.jpg",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/l7/022pxx22.xx22.140524123935.v2l7/catalogue/the-art-hub-kharghar-navi-mumbai-drawing-classes-gg5md.jpg",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/l7/022pxx22.xx22.140524123935.v2l7/catalogue/the-art-hub-kharghar-navi-mumbai-drawing-classes-bcz5i.jpg",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/l7/022pxx22.xx22.140524123935.v2l7/catalogue/the-art-hub-kharghar-navi-mumbai-drawing-classes-iucr5.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "40",
                    "P",
                    "S P Art Hub",
                    "Near Sai Baba Mandir Kharghar",
                    1,
                    0,
                    {
                        "id": 11235936,
                        "nid": 11235936,
                        "name": "Cartoon Drawing Classes"
                    },
                    "tfJbTArHpfBM9DNHXxHaRDfIAYATqbztNlvhzFAlX2I%3D",
                    "4.7",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.140524123935.V2L7",
                        "cmp_params": {
                            "bcity": "Navi Mumbai",
                            "barea": "Kharghar",
                            "bpncdbd": "410210",
                            "paidstatus": "6",
                            "misc": "8589934592",
                            "ask_mobile": 0
                        }
                    },
                    "SxEvXN8MsbHYT9%2FHIDsLJ60GHRCkhsDyFqw%2B0rmKh4w%3D",
                    0,
                    "Mumbai/S-P-Art-Hub-Near-Sai-Baba-Mandir-Kharghar/022PXX22-XX22-140524123935-V2L7_BZDET",
                    "Best Art In Navi Mumbai!! Perfect Guidance And Best Teachers.",
                    [
                        "Drawing Classes",
                        "Painting Classes"
                    ],
                    [
                        {
                            "tag_name": "Most searched",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/topsearch.svg"
                        }
                    ],
                    "",
                    {
                        "name": "Abhishek Yadav",
                        "rating": "5.0",
                        "review_date": "2021-11-05 03:22:18"
                    },
                    {},
                    [],
                    {
                        "lead": "48",
                        "lead_resp": "17",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "410210",
                    "",
                    {
                        "cname": "S P Art Hub",
                        "docid": "022PXX22.XX22.140524123935.V2L7",
                        "rating": "4.7",
                        "rating_cnt": "99",
                        "city": "Navi Mumbai",
                        "dcity": "Mumbai",
                        "area": "Kharghar",
                        "pin": "410210",
                        "ds": "0",
                        "pdg": "P",
                        "paid": "6",
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 1,
                        "tag": "Most searched",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": "20.598987912681785"
                    },
                    1,
                    "43SFBJYM"
                ],
                [
                    "022PXX22.XX22.200415012633.K3H1",
                    "Kutchi ITI",
                    "",
                    "Anand Koliwada Mumbra",
                    "19.185159",
                    "73.022047",
                    1,
                    "4.9",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 10:00 pm</span>",
                        "timing": "7:00 am - 10:00 pm"
                    },
                    "Mumbai Pune Road Mumbra",
                    1,
                    "Computer Training Institutes, Language Classes For English Conversation",
                    "07204993624",
                    "755",
                    "",
                    "mumbai",
                    "https://content.jdmagicbox.com/comp/mumbai/h1/022pxx22.xx22.200415012633.k3h1/catalogue/kutchi-iti-mumbra-thane-accounting-training-institutes-vb9zgyn1ye-250.jpg?clr=#491d1d",
                    "755",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">29 Years in Business</span>",
                            1,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.200415012633.K3H1.jpg",
                    "https://www.justdial.com/DT-43OBZZI5PED",
                    1,
                    [],
                    "",
                    2,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/mumbai/h1/022pxx22.xx22.200415012633.k3h1/catalogue/kutchi-iti-mumbra-thane-accounting-training-institutes-vb9zgyn1ye.jpg?clr=#491d1d",
                        "https://content.jdmagicbox.com/comp/thane/h1/022pxx22.xx22.200415012633.k3h1/catalogue/kutchi-iti-mumbra-thane-computer-training-institutes-for-accounting-w5oul56jlv.jpg",
                        "https://content.jdmagicbox.com/comp/thane/h1/022pxx22.xx22.200415012633.k3h1/catalogue/kutchi-iti-mumbra-thane-computer-training-institutes-for-accounting-wlco49c9s0.jpg",
                        "https://content.jdmagicbox.com/comp/thane/h1/022pxx22.xx22.200415012633.k3h1/catalogue/kutchi-iti-mumbra-thane-computer-training-institutes-for-accounting-b3use6ltfi.jpg",
                        "https://content.jdmagicbox.com/comp/thane/h1/022pxx22.xx22.200415012633.k3h1/catalogue/kutchi-iti-mumbra-thane-computer-training-institutes-for-accounting-yxot61v5ry.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "135",
                    "",
                    "Kutchi ITI",
                    "Anand Koliwada Mumbra",
                    1,
                    0,
                    {
                        "id": 10124307,
                        "nid": 10124307,
                        "name": "Accounting Training Institutes"
                    },
                    "vtvztjhjBFrw504IAMvGlcdhwuKkkiHgn2%2BNSIqaPP8%3D",
                    "4.9",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.200415012633.K3H1",
                        "cmp_params": {
                            "bcity": "Thane",
                            "barea": "Mumbra",
                            "bpncdbd": "400612",
                            "paidstatus": 1,
                            "misc": "8589942784",
                            "ask_mobile": 0
                        }
                    },
                    "p2P5IbXafx3YMYLlrZ14tYUM%2BrmGdk8EN1C%2BoWcov4o%3D",
                    0,
                    "Mumbai/Kutchi-ITI-Anand-Koliwada-Mumbra/022PXX22-XX22-200415012633-K3H1_BZDET",
                    "Kutchi ITI is an excellent coaching centre that offers a range of IT courses. The best part is that they offer interest-free EMI options, making it affordable for everyone. Their experienced trainers help students to gain practical knowledge and prepare them for the industry`s demands. Highly recommended!",
                    [
                        "Computer Training Institutes",
                        "Language Classes For English Conversation"
                    ],
                    [
                        {
                            "tag_name": "Trending",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg"
                        }
                    ],
                    "",
                    {
                        "name": "md Nuruddin",
                        "rating": "5.0",
                        "review_date": "2023-10-12 00:50:18"
                    },
                    {},
                    [],
                    {
                        "lead": "40",
                        "lead_resp": "33",
                        "avg_resp_time_sec": 4,
                        "tformat": "Hours",
                        "color": "#339D3A"
                    },
                    "400612",
                    "",
                    {
                        "cname": "Kutchi ITI",
                        "docid": "022PXX22.XX22.200415012633.K3H1",
                        "rating": "4.9",
                        "rating_cnt": "755",
                        "city": "Thane",
                        "dcity": "mumbai",
                        "area": "Mumbra",
                        "pin": "400612",
                        "ds": "0",
                        "pdg": "",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "1",
                        "pos": 2,
                        "tag": "Trending",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 18.6
                    },
                    1,
                    "43OBZZI5PED"
                ],
                [
                    "022PXX22.XX22.150813191319.E8H9",
                    "Revolution Fitness Academy",
                    "",
                    "Near 3 Star Hotel Kharghar",
                    "19.033789",
                    "73.065502",
                    1,
                    "4.6",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Available</span> <span class=\"font14 fw400 color111\"> until 6:00 pm</span>",
                        "timing": "10:00 am - 6:00 pm"
                    },
                    "Sector - 07 Kharghar",
                    1,
                    "Dietitians, Fitness Centres",
                    "",
                    "61",
                    "",
                    "Mumbai",
                    "https://content.jdmagicbox.com/comp/navi_mumbai/h9/022pxx22.xx22.150813191319.e8h9/catalogue/revolution-fitness-academy-kharghar-navi-mumbai-dietitians-s5d8-250.jpg?clr=#442233",
                    "61",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">8 Years in Healthcare</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [
                        {
                            "button_text": "Book Appointment",
                            "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/calendar_blue_icon.svg",
                            "button_url": [
                                {
                                    "url": "https://www.justdial.com/online-consult/hospital?docid=022PXX22.XX22.150813191319.E8H9&source=77&version=2.6&wap=77&action=BA&parentid=&extRdt=1&wkwebview=1&ll=rsltpge&ncatid=11251622&bcity=Navi+Mumbai&barea=Kharghar&bpncdbd=410210&paidstatus=1&misc=8592031744&ask_mobile=1&did=022PXX22.XX22.150813191319.E8H9&bd=1&city=Mumbai&area=&pncdbd=400706&is_verified=1&ncatid=11251622&search=Vocational+Course+Training+Centres&case=sms_email&frmpg=lspg&bdtoabd=",
                                    "text": "",
                                    "img": "",
                                    "dsc": ""
                                }
                            ],
                            "tp": "0",
                            "button_color": [],
                            "flag": 1,
                            "hide_header": "0",
                            "check": "appointment",
                            "skipVerif": "0",
                            "li": "Book Appointment"
                        }
                    ],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.150813191319.E8H9.jpg",
                    "https://www.justdial.com/DT-43EIUYEYI6U",
                    1,
                    [],
                    "",
                    3,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/navi_mumbai/h9/022pxx22.xx22.150813191319.e8h9/catalogue/revolution-fitness-academy-kharghar-navi-mumbai-dietitians-s5d8.jpg?clr=#442233",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/h9/022pxx22.xx22.150813191319.e8h9/catalogue/revolution-fitness-academy-kharghar-navi-mumbai-fitness-centres-fjthjma508.jpg",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/h9/022pxx22.xx22.150813191319.e8h9/catalogue/revolution-fitness-academy-kharghar-navi-mumbai-fitness-centres-4w4hij12jx.jpg",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/h9/022pxx22.xx22.150813191319.e8h9/catalogue/revolution-fitness-academy-kharghar-navi-mumbai-fitness-centres-rjabzrhu0c.jpg",
                        "https://content.jdmagicbox.com/comp/navi-mumbai/h9/022pxx22.xx22.150813191319.e8h9/catalogue/revolution-fitness-academy-kharghar-navi-mumbai-fitness-centres-siw9rr3kaw.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "25",
                    "V",
                    "Revolution Fitness Academy",
                    "Near 3 Star Hotel Kharghar",
                    1,
                    1,
                    {
                        "id": 10208976,
                        "nid": 10208976,
                        "name": "Fitness Centres"
                    },
                    "ill%2F5I2N2RVuHgOA%2FRhCpa7pQrASGg4m4PaLDbfX474%3D",
                    "4.6",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.150813191319.E8H9",
                        "cmp_params": {
                            "bcity": "Navi Mumbai",
                            "barea": "Kharghar",
                            "bpncdbd": "410210",
                            "paidstatus": 1,
                            "misc": "8592031744",
                            "ask_mobile": 1
                        }
                    },
                    "u%2ByeTkpetJZde9D%2BZsefIb20ls1cbnmlx0XxsXE6c3I%3D",
                    0,
                    "Mumbai/Revolution-Fitness-Academy-Near-3-Star-Hotel-Kharghar/022PXX22-XX22-150813191319-E8H9_BZDET",
                    "Great learning experience with the teachers.\ndoubts are never ignored.\nalways supplied as with additional information through out the course.\ncan highly recommend rfa to be an fitness professional.\ntons of courses are provided at great rates",
                    [
                        "Weight Gain Program",
                        "Nutrition Consultation",
                        "Get Your Own Trainer"
                    ],
                    [
                        {
                            "tag_name": "Trending",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg"
                        }
                    ],
                    "",
                    {
                        "name": "Nikhil Boloor",
                        "rating": "5.0",
                        "review_date": "2023-01-18 13:23:48"
                    },
                    {},
                    [],
                    {
                        "lead": "5",
                        "lead_resp": "1",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "410210",
                    "",
                    {
                        "cname": "Revolution Fitness Academy",
                        "docid": "022PXX22.XX22.150813191319.E8H9",
                        "rating": "4.6",
                        "rating_cnt": "61",
                        "city": "Navi Mumbai",
                        "dcity": "Mumbai",
                        "area": "Kharghar",
                        "pin": "410210",
                        "ds": "0",
                        "pdg": "V",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 3,
                        "tag": "Trending",
                        "cta_name": "Book Appointment",
                        "call_cta": "2",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 20.91
                    },
                    1,
                    "43EIUYEYI6U"
                ],
                [
                    "022P8010204",
                    "Anandi Special School",
                    "",
                    "Near Parle G Company Vile Parle East",
                    "19.106666666667",
                    "72.847777777778",
                    1,
                    "4.2",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Available</span> <span class=\"font14 fw400 color111\"> until 6:00 pm</span>",
                        "timing": "10:00 am - 6:00 pm"
                    },
                    "Raje Marg Vile Parle East",
                    1,
                    "Schools, Tutorials",
                    "",
                    "31",
                    "",
                    "Mumbai",
                    "https://content.jdmagicbox.com/comp/mumbai/04/022p8010204/catalogue/anandi-special-school-mumbai-sh3pcqz2gs-250.jpg?clr=#333333",
                    "31",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">18 Years in Healthcare</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [
                        {
                            "button_text": "Book Appointment",
                            "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/calendar_blue_icon.svg",
                            "button_url": [
                                {
                                    "url": "https://www.justdial.com/online-consult/hospital?docid=022P8010204&source=77&version=2.6&wap=77&action=BA&parentid=&extRdt=1&wkwebview=1&ll=rsltpge&ncatid=11251622&bcity=Mumbai&barea=Vile+Parle+East&bpncdbd=400057&paidstatus=1&misc=8592031748&ask_mobile=1&did=022P8010204&bd=1&city=Mumbai&area=&pncdbd=400706&is_verified=1&ncatid=11251622&search=Vocational+Course+Training+Centres&case=sms_email&frmpg=lspg&bdtoabd=",
                                    "text": "",
                                    "img": "",
                                    "dsc": ""
                                }
                            ],
                            "tp": "0",
                            "button_color": [],
                            "flag": 1,
                            "hide_header": "0",
                            "check": "appointment",
                            "skipVerif": "0",
                            "li": "Book Appointment"
                        }
                    ],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022P8010204.jpg",
                    "https://www.justdial.com/DT-435PFNX2",
                    1,
                    [],
                    "",
                    4,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/mumbai/04/022p8010204/catalogue/anandi-special-school-mumbai-sh3pcqz2gs.jpg?clr=#333333",
                        "https://content.jdmagicbox.com/comp/mumbai/04/022p8010204/catalogue/anandi-special-school-vile-parle-east-mumbai-behaviour-therapy-doctors-c6tp2.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/04/022p8010204/catalogue/anandi-special-school-vile-parle-east-mumbai-behaviour-therapy-doctors-uik3k.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/04/022p8010204/catalogue/anandi-special-school-vile-parle-east-mumbai-behaviour-therapy-doctors-3u6c443.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/04/022p8010204/catalogue/anandi-special-school-vile-parle-east-mumbai-behaviour-therapy-doctors-ed08t5.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "15",
                    "V",
                    "Anandi Special School",
                    "Near Parle G Company Vile Parle East",
                    1,
                    1,
                    {
                        "id": 10857298,
                        "nid": 10857298,
                        "name": "Admission Consultants"
                    },
                    "X4FSqBR8Plv6oqfrpqJPrA%3D%3D",
                    "4.2",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022P8010204",
                        "cmp_params": {
                            "bcity": "Mumbai",
                            "barea": "Vile Parle East",
                            "bpncdbd": "400057",
                            "paidstatus": 1,
                            "misc": "8592031748",
                            "ask_mobile": 1
                        }
                    },
                    "SKdKukM%2F%2B3S5kVUxKoOyKO%2Byw3vlKrkE8Bdpc79rd0k%3D",
                    0,
                    "Mumbai/Anandi-Special-School-Near-Parle-G-Company-Vile-Parle-East/022P8010204_BZDET",
                    "Its very good school,really working for betterment of handicapped children focused with study. All therapies and vocational courses.",
                    [
                        "Violent Behavior"
                    ],
                    [],
                    "",
                    {
                        "name": "sanjay ranade",
                        "rating": "4.0",
                        "review_date": "2011-09-22 09:19:59"
                    },
                    {},
                    [],
                    {
                        "lead": "18",
                        "lead_resp": "0",
                        "avg_resp_time_sec": ""
                    },
                    "400057",
                    "",
                    {
                        "cname": "Anandi Special School",
                        "docid": "022P8010204",
                        "rating": "4.2",
                        "rating_cnt": "31",
                        "city": "Mumbai",
                        "dcity": "Mumbai",
                        "area": "Vile Parle East",
                        "pin": "400057",
                        "ds": "0",
                        "pdg": "V",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 4,
                        "tag": "",
                        "cta_name": "Book Appointment",
                        "call_cta": "2",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 3.47
                    },
                    1,
                    "435PFNX2"
                ],
                [
                    "022PXX22.XX22.181007181027.R5V5",
                    "I-Tech Computer Education",
                    "",
                    "Opposite Panchmukhi Hanuman Mandir Nalasopara West",
                    "19.420519972222",
                    "72.81528",
                    1,
                    "4.5",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 9:30 pm</span>",
                        "timing": "7:00 am - 9:30 pm"
                    },
                    "Station Road Nalasopara West",
                    1,
                    "Tutorials, Computer Training Institutes",
                    "09972233349",
                    "630",
                    "1",
                    "Mumbai",
                    "https://content.jdmagicbox.com/comp/palghar/v5/022pxx22.xx22.181007181027.r5v5/catalogue/i-tech-computer-education-nalasopara-west-palghar-computer-training-institutes-sxhi3mq4sn-250.jpg?clr=#123354",
                    "630",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">12 Years in Business</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.181007181027.R5V5.jpg",
                    "https://www.justdial.com/DT-43U6EM6M6QA",
                    1,
                    [],
                    "",
                    5,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/palghar/v5/022pxx22.xx22.181007181027.r5v5/catalogue/i-tech-computer-education-nalasopara-west-palghar-computer-training-institutes-sxhi3mq4sn.jpg?clr=#123354",
                        "https://content.jdmagicbox.com/comp/mumbai/v5/022pxx22.xx22.181007181027.r5v5/catalogue/i-tech-computer-education-nalasopara-west-mumbai-computer-training-institutes-83mjnet4wo.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/v5/022pxx22.xx22.181007181027.r5v5/catalogue/i-tech-computer-education-nalasopara-west-mumbai-computer-training-institutes-2bk74av2ic.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/v5/022pxx22.xx22.181007181027.r5v5/catalogue/i-tech-computer-education-nalasopara-west-mumbai-computer-training-institutes-nkndmfbc0j.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/v5/022pxx22.xx22.181007181027.r5v5/catalogue/i-tech-computer-education-nalasopara-west-mumbai-computer-training-institutes-kqurxmzk7a.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "50",
                    "",
                    "I-Tech Computer Education",
                    "Opposite Panchmukhi Hanuman Mandir Nalasopara West",
                    1,
                    0,
                    {
                        "id": 10124277,
                        "nid": 10124277,
                        "name": "Computer Training Institutes"
                    },
                    "jN9u0NDl1N1qSo9xri3yeBec12y6qXKlm%2BV4AU7Mo%2Fk%3D",
                    "4.5",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.181007181027.R5V5",
                        "cmp_params": {
                            "bcity": "Palghar",
                            "barea": "Nalasopara West",
                            "bpncdbd": "401203",
                            "paidstatus": 1,
                            "misc": "8589934596",
                            "ask_mobile": 0
                        }
                    },
                    "RgidDWrew1FhuYMWDXtp97N3fYaM4t5DBClLWATeKRg%3D",
                    0,
                    "Mumbai/I-Tech-Computer-Education-Opposite-Panchmukhi-Hanuman-Mandir-Nalasopara-West/022PXX22-XX22-181007181027-R5V5_BZDET",
                    "I am an DCA student...my faculty name is mala mam....I am satisfied with classes...all teachers clear the doubt very easily........I ask multiple time...and they solve it...thanku ITech❤️",
                    [
                        "Tutorials",
                        "Computer Training Institutes"
                    ],
                    [
                        {
                            "tag_name": "Top rated",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/toprated.svg"
                        }
                    ],
                    "",
                    {
                        "name": "Ruchi Shukla",
                        "rating": "5.0",
                        "review_date": "2023-08-22 19:24:12"
                    },
                    {},
                    [],
                    {
                        "lead": "36",
                        "lead_resp": "25",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "401203",
                    "",
                    {
                        "cname": "I-Tech Computer Education",
                        "docid": "022PXX22.XX22.181007181027.R5V5",
                        "rating": "4.5",
                        "rating_cnt": "630",
                        "city": "Palghar",
                        "dcity": "Mumbai",
                        "area": "Nalasopara West",
                        "pin": "401203",
                        "ds": "0",
                        "pdg": "",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 5,
                        "tag": "Top rated",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 37.26
                    },
                    1,
                    "43U6EM6M6QA"
                ],
                [
                    "022PXX22.XX22.230707173438.L3H1",
                    "Om Creations Trust (Om Abode)",
                    "",
                    "Near Famous Studio Mahalaxmi",
                    "18.990991583333",
                    "72.828964222222",
                    1,
                    "4.6",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 7:00 pm</span>",
                        "timing": "8:00 am - 7:00 pm"
                    },
                    "Dr E Moses Road Mahalaxmi",
                    1,
                    "Vocational Course Training Centres, Institutes For Skill Development",
                    "07947156877",
                    "63",
                    "",
                    "mumbai",
                    "https://content.jdmagicbox.com/comp/mumbai/h1/022pxx22.xx22.230707173438.l3h1/catalogue/om-creations-trust-om-abode-mahalaxmi-mumbai-vocational-course-training-centres-a61dfuh89q-250.jpg?clr=#471f1f",
                    "63",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">32 Years in Business</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.230707173438.L3H1.jpg",
                    "https://www.justdial.com/DT-43CSE9DDXWG",
                    1,
                    [],
                    "",
                    6,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/mumbai/h1/022pxx22.xx22.230707173438.l3h1/catalogue/om-creations-trust-om-abode-mahalaxmi-mumbai-vocational-course-training-centres-a61dfuh89q.jpg?clr=#471f1f",
                        "https://content.jdmagicbox.com/comp/mumbai/h1/022pxx22.xx22.230707173438.l3h1/catalogue/rhez8p0wbsxwssp-b7tx6c71cw.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/81/022p2150281/catalogue/om-creations-trust-mahalaxmi-mumbai-ngos-for-women-lvhrnxmszd.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/81/022p2150281/catalogue/om-creations-trust-mahalaxmi-mumbai-ngos-14r8b1l.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "11",
                    "",
                    "Om Creations Trust (Om Abode)",
                    "Near Famous Studio Mahalaxmi",
                    1,
                    0,
                    {
                        "id": 11251622,
                        "nid": 11251622,
                        "name": "Vocational Course Training Centres"
                    },
                    "ugf9qLPLUneA8fkNqxxRz8nTEzruoEFHfS4u7tgxrNI%3D",
                    "4.6",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.230707173438.L3H1",
                        "cmp_params": {
                            "bcity": "Mumbai",
                            "barea": "Mahalaxmi",
                            "bpncdbd": "400011",
                            "paidstatus": 1,
                            "misc": "0",
                            "ask_mobile": 0
                        }
                    },
                    "Nky3pjSZTjoebhbdPiL7xv3xNSeDBnGl2%2Bh9eZ2Snvw%3D",
                    0,
                    "Mumbai/Om-Creations-Trust-Om-Abode-Near-Famous-Studio-Mahalaxmi/022PXX22-XX22-230707173438-L3H1_BZDET",
                    "",
                    [
                        "Vocational Course Training Centres",
                        "Institutes For Skill Development"
                    ],
                    [
                        {
                            "tag_name": "Trending",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg"
                        }
                    ],
                    "",
                    [],
                    {},
                    [],
                    {
                        "lead": "59",
                        "lead_resp": "2",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "400011",
                    "",
                    {
                        "cname": "Om Creations Trust (Om Abode)",
                        "docid": "022PXX22.XX22.230707173438.L3H1",
                        "rating": "4.6",
                        "rating_cnt": "63",
                        "city": "Mumbai",
                        "dcity": "mumbai",
                        "area": "Mahalaxmi",
                        "pin": "400011",
                        "ds": "0",
                        "pdg": "",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 6,
                        "tag": "Trending",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 12.16
                    },
                    1,
                    "43CSE9DDXWG"
                ],
                [
                    "022PXX22.XX22.190612093002.P1P2",
                    "Addhyayan Institute",
                    "",
                    "Apna Bazar Kandivali West",
                    "19.215980527778",
                    "72.828407277778",
                    1,
                    "4.7",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 10:00 pm</span>",
                        "timing": "7:00 am - 10:00 pm"
                    },
                    "Charkop Market Kandivali West",
                    1,
                    "Tutorials, Computer Training Institutes",
                    "09972268260",
                    "62",
                    "",
                    "mumbai",
                    "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.190612093002.p1p2/catalogue/addhyayan-institute-kandivali-west-mumbai-computer-hardware-training-institutes-tucqbvwjk8-250.jpg?clr=#3a2c3a",
                    "62",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">35 Years in Business</span>",
                            1,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.190612093002.P1P2.jpg",
                    "https://www.justdial.com/DT-43UUEIAIE2Y",
                    1,
                    [],
                    "",
                    7,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.190612093002.p1p2/catalogue/addhyayan-institute-kandivali-west-mumbai-computer-hardware-training-institutes-tucqbvwjk8.jpg?clr=#3a2c3a",
                        "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.190612093002.p1p2/catalogue/addhyayan-institute-kandivali-west-mumbai-computer-training-institutes-for-basic-7si73xanbx.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.190612093002.p1p2/catalogue/addhyayan-institute-kandivali-west-mumbai-computer-training-institutes-for-basic-l09yoy2d43.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.190612093002.p1p2/catalogue/addhyayan-institute-kandivali-west-mumbai-computer-training-institutes-for-basic-fszouhi7be.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.190612093002.p1p2/catalogue/addhyayan-institute-kandivali-west-mumbai-computer-training-institutes-for-basic-tle2r0rs2m.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "160",
                    "",
                    "Addhyayan Institute",
                    "Apna Bazar Kandivali West",
                    1,
                    0,
                    {
                        "id": 10124390,
                        "nid": 10124390,
                        "name": "Computer Training Institutes For Basic"
                    },
                    "JnqNX9JkIkhRdzNJp3aBxnB%2B0XjIciGzUIz6CVL7LI8%3D",
                    "4.7",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.190612093002.P1P2",
                        "cmp_params": {
                            "bcity": "Mumbai",
                            "barea": "Kandivali West",
                            "bpncdbd": "400067",
                            "paidstatus": 1,
                            "misc": "8589942788",
                            "ask_mobile": 0
                        }
                    },
                    "BrqVlMKOCTgvuj9nBV86Nje%2FxtQjpjGbT%2B6ZZ2SNaMA%3D",
                    0,
                    "Mumbai/Addhyayan-Institute-Apna-Bazar-Kandivali-West/022PXX22-XX22-190612093002-P1P2_BZDET",
                    "",
                    [
                        "Tutorials",
                        "Computer Training Institutes"
                    ],
                    [
                        {
                            "tag_name": "Trending",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg"
                        }
                    ],
                    "",
                    [],
                    {},
                    [],
                    {
                        "lead": "95",
                        "lead_resp": "3",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "400067",
                    "",
                    {
                        "cname": "Addhyayan Institute",
                        "docid": "022PXX22.XX22.190612093002.P1P2",
                        "rating": "4.7",
                        "rating_cnt": "62",
                        "city": "Mumbai",
                        "dcity": "mumbai",
                        "area": "Kandivali West",
                        "pin": "400067",
                        "ds": "0",
                        "pdg": "",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "1",
                        "pos": 7,
                        "tag": "Trending",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 14.82
                    },
                    1,
                    "43UUEIAIE2Y"
                ],
                [
                    "022PXX22.XX22.000439459895.P8P4",
                    "Industrial Engineering Institute",
                    "",
                    "Behind Ashok Cinema Near Datta Mandir and Thane College Road Thane West",
                    "19.1882753",
                    "72.9782128",
                    1,
                    "4",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 8:00 pm</span>",
                        "timing": "8:00 am - 8:00 pm"
                    },
                    "R S Road Thane West",
                    1,
                    "Computer Training Institutes, AUTOCAD Training Institutes",
                    "09036695653",
                    "106",
                    "",
                    "Mumbai",
                    "https://content.jdmagicbox.com/comp/thane/p4/022pxx22.xx22.000439459895.p8p4/catalogue/industrial-engineering-institute-thane-west-thane-vocational-course-training-centres-3clsovb-250.jpg?clr=#491d2c",
                    "106",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">58 Years in Business</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.000439459895.P8P4.jpg",
                    "https://www.justdial.com/DT-43VSU7JW",
                    1,
                    [],
                    "",
                    8,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/thane/p4/022pxx22.xx22.000439459895.p8p4/catalogue/industrial-engineering-institute-thane-west-thane-vocational-course-training-centres-3clsovb.jpg?clr=#491d2c",
                        "https://content.jdmagicbox.com/comp/mumbai/p4/022pxx22.xx22.000439459895.p8p4/catalogue/industrial-engineering-institute-thane-west-mumbai-computer-training-institutes-for-adobe-photoshop-tp4jiya0xe.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/p4/022pxx22.xx22.000439459895.p8p4/catalogue/industrial-engineering-institute-thane-west-mumbai-adobe-photoshop-training-institutes-rup75axeh6.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/p4/022pxx22.xx22.000439459895.p8p4/catalogue/industrial-engineering-institute-thane-west-mumbai-adobe-photoshop-training-institutes-c5i7ul4v2u.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/p4/022pxx22.xx22.000439459895.p8p4/catalogue/industrial-engineering-institute-thane-west-mumbai-adobe-photoshop-training-institutes-54envcbv4l.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "29",
                    "",
                    "Industrial Engineering Institute",
                    "Behind Ashok Cinema Near Datta Mandir and Thane College Road Thane West",
                    1,
                    0,
                    {
                        "id": 10124326,
                        "nid": 10124326,
                        "name": "Adobe Photoshop Training Institutes"
                    },
                    "5whiYUlRJWZe7Sc5vj6IT8M1%2Fj%2F3Rmk%2FS%2BGvndkWpCg%3D",
                    "4",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.000439459895.P8P4",
                        "cmp_params": {
                            "bcity": "Thane",
                            "barea": "Thane West",
                            "bpncdbd": "400601",
                            "paidstatus": 1,
                            "misc": "8589934596",
                            "ask_mobile": 0
                        }
                    },
                    "LPrAYezqSEvCaQgGzGAQIA1BJ2L%2BTrETnvvEbZo0WXw%3D",
                    0,
                    "Mumbai/Industrial-Engineering-Institute-Behind-Ashok-Cinema-Near-Datta-Mandir-and-Thane-College-Road-Thane-West/022PXX22-XX22-000439459895-P8P4_BZDET",
                    "They are just too good. Simple and polite way of teaching. Extremely supportive professors. Location is very close to thane stn. simply excellent, but preferably should join regular batch instead of weekend, for more knowledge..",
                    [
                        "Computer Training Institutes",
                        "AUTOCAD Training Institutes"
                    ],
                    [
                        {
                            "tag_name": "Quick Response",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/responsive.svg"
                        }
                    ],
                    "",
                    {
                        "name": "rajkumari",
                        "rating": "4.5",
                        "review_date": "2019-02-03 22:46:55"
                    },
                    {},
                    [],
                    {
                        "lead": "83",
                        "lead_resp": "24",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "400601",
                    "",
                    {
                        "cname": "Industrial Engineering Institute",
                        "docid": "022PXX22.XX22.000439459895.P8P4",
                        "rating": "4",
                        "rating_cnt": "106",
                        "city": "Thane",
                        "dcity": "Mumbai",
                        "area": "Thane West",
                        "pin": "400601",
                        "ds": "0",
                        "pdg": "",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 8,
                        "tag": "Quick Response",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 15.27
                    },
                    1,
                    "43VSU7JW"
                ],
                [
                    "022PXX22.XX22.220807130031.V6N4",
                    "Ishwari Nursing Institute",
                    "",
                    "Opposite Vidya Mandir School Above Titwala Post Office Manda",
                    "19.294691666667",
                    "73.203633333333",
                    1,
                    "4",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 8:00 pm</span>",
                        "timing": "8:00 am - 8:00 pm"
                    },
                    "Titwala-ambivali Road Manda",
                    1,
                    "Tutorials, Institutes",
                    "08904229802",
                    "6",
                    "",
                    "mumbai",
                    "https://content.jdmagicbox.com/comp/mumbai/n4/022pxx22.xx22.220807130031.v6n4/catalogue/ishwari-academy-manda-thane-institutes-rk4tlo1wqm-250.jpg?clr=#4c1a1a",
                    "6",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">3 Years in Business</span>",
                            1,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.220807130031.V6N4.jpg",
                    "https://www.justdial.com/DT-4375EWQ8UM2",
                    1,
                    [],
                    "",
                    9,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/mumbai/n4/022pxx22.xx22.220807130031.v6n4/catalogue/ishwari-academy-manda-thane-institutes-rk4tlo1wqm.jpg?clr=#4c1a1a",
                        "https://content.jdmagicbox.com/comp/mumbai/n4/022pxx22.xx22.220807130031.v6n4/catalogue/ishwari-nursing-institute-manda-mumbai-institutes-q072zsyq98.jpg",
                        "https://content.jdmagicbox.com/comp/mumbai/n4/022pxx22.xx22.220807130031.v6n4/catalogue/ishwari-nursing-institute-manda-mumbai-institutes-yeualy5hnm.jpg",
                        "https://content.jdmagicbox.com/comp/service_catalogue/ishwari-nursing-institute-titwala-022pxx22.xx22.220807130031.v6n4-fta7fpx.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "4",
                    "",
                    "Ishwari Nursing Institute",
                    "Opposite Vidya Mandir School Above Titwala Post Office Manda",
                    1,
                    0,
                    {
                        "id": 10268288,
                        "nid": 10268288,
                        "name": "Institutes"
                    },
                    "qFGZSGSdaythoLP4%2B3TuaAoOxxOhpgc6XAi8XuSV7Xg%3D",
                    "4",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "022PXX22.XX22.220807130031.V6N4",
                        "cmp_params": {
                            "bcity": "Thane",
                            "barea": "Manda",
                            "bpncdbd": "421605",
                            "paidstatus": 1,
                            "misc": "8589942788",
                            "ask_mobile": 0
                        }
                    },
                    "pZjQO9wZENakCTTBE59%2FkV9a41bx02%2B%2FH2FOB0s4Tpw%3D",
                    0,
                    "Mumbai/Ishwari-Nursing-Institute-Opposite-Vidya-Mandir-School-Above-Titwala-Post-Office-Manda/022PXX22-XX22-220807130031-V6N4_BZDET",
                    "This institution is help for the poor people to learn in this nursing college because of GNM Nursing and BSc nursing helping to make their future bright with professional course.It is having the facilities very nice compared to the other colleges hav..",
                    [
                        "Tutorials",
                        "Institutes"
                    ],
                    [],
                    "",
                    {
                        "name": "sheetal more",
                        "rating": "5.0",
                        "review_date": "2023-02-22 16:39:34"
                    },
                    {},
                    [],
                    {
                        "lead": "18",
                        "lead_resp": "7",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "421605",
                    "",
                    {
                        "cname": "Ishwari Nursing Institute",
                        "docid": "022PXX22.XX22.220807130031.V6N4",
                        "rating": "4",
                        "rating_cnt": "6",
                        "city": "Thane",
                        "dcity": "mumbai",
                        "area": "Manda",
                        "pin": "421605",
                        "ds": "0",
                        "pdg": "",
                        "paid": 1,
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "1",
                        "pos": 9,
                        "tag": "",
                        "cta_name": "Enquire Now",
                        "call_cta": "3",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": 41.24
                    },
                    1,
                    "4375EWQ8UM2"
                ],
                [
                    "9999PX294.X294.140129101202.N7A7",
                    "Visvesvaraya Foundation",
                    "",
                    "Opposite Hansa Palace Udaipur City",
                    "24.571123",
                    "73.722369972222",
                    "1",
                    "4.2",
                    "1",
                    1,
                    "1",
                    {
                        "status": "<span class=\"font14 fw400 els color339\">Open</span> <span class=\"font14 fw400 color111\"> until 5:00 pm</span>",
                        "timing": "9:30 am - 5:00 pm"
                    },
                    "Udaipur-rajasthan,Udaipur City",
                    1,
                    "Colleges, Tutorials",
                    "",
                    "945",
                    "",
                    "Udaipur-Rajasthan",
                    "https://content.jdmagicbox.com/comp/udaipur-rajasthan/a7/9999px294.x294.140129101202.n7a7/catalogue/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-colleges-1001htsbgd-250.jpg?clr=#333333",
                    "945",
                    0,
                    {
                        "node1": "",
                        "node2": "",
                        "node3": [
                            "<span class=\"font14 fw400 color111\">19 Years in Business</span>",
                            0,
                            0
                        ],
                        "node1color": []
                    },
                    {},
                    0,
                    0,
                    [],
                    "other",
                    "",
                    [],
                    "",
                    "https://content2.jdmagicbox.com/checkin/udaipur-rajasthan/9999PX294.X294.140129101202.N7A7.jpg",
                    "https://www.justdial.com/DT-993WDAM7",
                    1,
                    [],
                    "",
                    10,
                    "",
                    "",
                    "",
                    [
                        "https://content.jdmagicbox.com/comp/udaipur-rajasthan/a7/9999px294.x294.140129101202.n7a7/catalogue/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-colleges-1001htsbgd.jpg?clr=#333333",
                        "https://content.jdmagicbox.com/comp/udaipur-rajasthan/a7/9999px294.x294.140129101202.n7a7/catalogue/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-computer-engineering-colleges-exs28pzu5s.jpg",
                        "https://content.jdmagicbox.com/comp/udaipur-rajasthan/a7/9999px294.x294.140129101202.n7a7/catalogue/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-colleges-nr2u3xt.jpg",
                        "https://content.jdmagicbox.com/comp/udaipur-rajasthan/a7/9999px294.x294.140129101202.n7a7/catalogue/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-colleges-zqf4rix.jpg",
                        "https://content.jdmagicbox.com/comp/udaipur-rajasthan/a7/9999px294.x294.140129101202.n7a7/catalogue/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-colleges-o290zwm.jpg"
                    ],
                    [
                        0,
                        0,
                        0
                    ],
                    "23",
                    "V",
                    "Visvesvaraya Foundation",
                    "Opposite Hansa Palace Udaipur City",
                    1,
                    1,
                    {
                        "id": 10106406,
                        "nid": 10106406,
                        "name": "Computer Engineering Colleges"
                    },
                    "1r4cdLdMM8AW8kLfaMMoaroiU9BhdrdJhMP0tvWk5KS1%2BAGSxtgI8Z80iwhieaQn",
                    "4.2",
                    0,
                    {
                        "img": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
                        "redirection_url": ""
                    },
                    {},
                    "0",
                    1,
                    {
                        "did": "9999PX294.X294.140129101202.N7A7",
                        "cmp_params": {
                            "bcity": "Udaipur-Rajasthan",
                            "barea": "Udaipur City",
                            "bpncdbd": "313001",
                            "paidstatus": "1",
                            "misc": "8592031748",
                            "ask_mobile": 1
                        }
                    },
                    "2ka%2FswruvXAhSWKmoLqFUDzFEk7DBFfMfvb5vO6i3iA%3D",
                    0,
                    "Udaipur-rajasthan/Visvesvaraya-Foundation-Opposite-Hansa-Palace-Udaipur-City/9999PX294-X294-140129101202-N7A7_BZDET",
                    "This was my first time taking classes in this format and it far exceeded my expectations ,very cooperating faculty,quality education with peaceful atmosphere to study.Time to time motivation to enhance the moral of the aspirants  by the all teachers.",
                    [
                        "Colleges",
                        "Tutorials"
                    ],
                    [
                        {
                            "tag_name": "Popular",
                            "bg_colour": "#5271dd",
                            "txt_colour": "#FFFFFF",
                            "tag_image": "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/popular.svg"
                        }
                    ],
                    "",
                    {
                        "name": "Abhishek Rana",
                        "rating": "5.0",
                        "review_date": "2023-02-28 11:29:55"
                    },
                    {},
                    [],
                    {
                        "lead": "170",
                        "lead_resp": "33",
                        "avg_resp_time_sec": "",
                        "tformat": "",
                        "color": "#339D3A"
                    },
                    "313001",
                    "",
                    {
                        "cname": "Visvesvaraya Foundation",
                        "docid": "9999PX294.X294.140129101202.N7A7",
                        "rating": "4.2",
                        "rating_cnt": "945",
                        "city": "Udaipur-Rajasthan",
                        "dcity": "Udaipur-Rajasthan",
                        "area": "Udaipur City",
                        "pin": "313001",
                        "ds": "0",
                        "pdg": "V",
                        "paid": "1",
                        "jd_verified": "1",
                        "guarantee": "",
                        "trust": "0",
                        "verified": "0",
                        "pos": 10,
                        "tag": "Popular",
                        "cta_name": "Enquire Now",
                        "call_cta": "2",
                        "deals": "",
                        "jd_cash": "",
                        "isb2b": "0",
                        "miscellaneous_flag": "9",
                        "distance": "",
                        "core_distance": "616.30"
                    },
                    1,
                    "993WDAM7"
                ]
            ],
            "rvs": []
        },
        "nearmeDetails": "",
        "catid": "",
        "trending_flag": 0,
        "trending_nid": "",
        "keyword": " Vocational Course Training Centres",
        "keywordln": " Vocational Course Training Centres",
        "ishotel": 0,
        "keywordResults": [],
        "moreKeywords": "0",
        "totalNumberofResults": "100",
        "sortingOption": {
            "basedon": [
                "distance",
                "rating",
                "popular"
            ],
            "sort": "",
            "char": "",
            "morefilter": {
                "mv": "1102",
                "mh": "Quick Filters",
                "md": "",
                "ms": 1,
                "d": [
                    {
                        "v": "HR",
                        "d": "Rated 3.5+",
                        "f": 1,
                        "s": 0,
                        "nc": null,
                        "n": null,
                        "e": "6"
                    },
                    {
                        "v": "OPEN",
                        "d": "Open Now",
                        "f": 1,
                        "s": 0,
                        "nc": null,
                        "n": null,
                        "e": "10"
                    }
                ]
            },
            "pricefilter": ""
        },
        "ratingsTab": 0,
        "pncdbd": "400706",
        "ismovie": "0",
        "sort_price_tag": null,
        "advanced_bd_flag": "0",
        "sort_price": null,
        "filter_flag": "0",
        "image_path": "https://akam.cdn.jdmagicbox.com/images/jdcategories/0.jpg",
        "view": "0",
        "national_catid": "11251622",
        "median_latitude": 19.09075,
        "median_longitude": 72.87611,
        "seo_dt": {
            "title": "Top Vocational Course Training Centres in Mumbai - Best Vocational Course Training Centers near me - Justdial",
            "desc": "137 Vocational Course Training Centres in Mumbai. Find ✓Tutorials, ✓Computer Training Institutes, ✓Institutes, ✓Digital Marketing Courses, ✓Institutes For Mobile Phone Servicing in Mumbai. Get Phone Numbers, Address, Reviews, Photos, Maps , FAQs for top Vocational Course Training Centres near me in Mumbai on Justdial.",
            "key": "List of Vocational Course Training Centres in Mumbai, Reviews, Map, Address, Phone Number, Contact Number, local, popular Vocational Course Training Centres, Vocational Course Training Centres",
            "isfreetext": 0,
            "hot_cat_arr": {
                "id": 11235936,
                "nid": 11235936,
                "name": "Cartoon Drawing Classes"
            },
            "area": null,
            "link": "https://www.justdial.com/Mumbai/Vocational-Course-Training-Centres/nct-11251622"
        },
        "vpfs": "",
        "msgpos": "",
        "areadocids": "",
        "area_docids_cnt": "",
        "nofriends": "",
        "nextdocid": "022PXX22.XX22.140524123935.V2L7,022PXX22.XX22.200415012633.K3H1,022PXX22.XX22.150813191319.E8H9,022P8010204,022PXX22.XX22.181007181027.R5V5,022PXX22.XX22.230707173438.L3H1,022PXX22.XX22.190612093002.P1P2,022PXX22.XX22.000439459895.P8P4,022PXX22.XX22.220807130031.V6N4,9999PX294.X294.140129101202.N7A7,0141PX141.X141.110218182419.A5N4,022PXX22.XX22.141107145654.A4W3,022PGL01532,022PXX22.XX22.200121125802.C2I9,022PXX22.XX22.190912113011.T1V8,022PXX22.XX22.161118194309.P3P2,022PXX22.XX22.120623163942.U1W8,022PXX22.XX22.111216113945.B7D7,022PXX22.XX22.181120210022.J9J1,022PXX22.XX22.130417075534.U5B7,022PXX22.XX22.200318190452.S4X9,022P8805260,022PJDYP22039490,022PXX22.XX22.211124091235.P7Y3,022PXX22.XX22.140124161434.D4A8,022PXX22.XX22.190511141944.Z8E1,022PXX22.XX22.090825153514.I6A3,022PXX22.XX22.130508133036.W1M3,022PXX22.XX22.110123163329.D6J5,022PXX22.XX22.141113163703.K7Q2,022PXX22.XX22.140420214011.Y6N1,022PXX22.XX22.230107103954.R1Y3,022P860322,022PXX22.XX22.130228122444.N5L1,022PXX22.XX22.121218151546.Q9G9,022P8401546,022PXX22.XX22.140616095419.G5J3,022PXX22.XX22.171115131118.C2E4,022PXX22.XX22.170427131626.Z9P9,022PXX22.XX22.001088663606.P4M0,022PXX22.XX22.190624173005.W1P9,022PXX22.XX22.180704155748.A9X4,022PXX22.XX22.220327133449.Y3M7,022PXX22.XX22.210621144017.K3T5,022PXX22.XX22.190516122621.Z8J9,022PXX22.XX22.171225143510.F4R2,022PXX22.XX22.130316204513.X4G8,022PXX22.XX22.130620112624.R4N8,022PXX22.XX22.180718173656.H9M5,022PXX22.XX22.190117191953.A1C3,022P5665813,022PXX22.XX22.160722103037.M2E5,022PXX22.XX22.180411184817.P8T4,022PXX22.XX22.180621123134.B6F7,022PXX22.XX22.170111121643.F7N7,022PXX22.XX22.121208113946.R9D2,022PXX22.XX22.130520110019.Z2F9,022PXX22.XX22.130703103300.Z2B1,022PS000560,022PXX22.XX22.180323161026.H9V2,022PXX22.XX22.180123141550.J9I7,022PXX22.XX22.180901061735.W6T5,022PXX22.XX22.111107150210.T4V1,022PXX22.XX22.170715153605.K1Q1,022PXX22.XX22.150728154430.B5J4,022PXX22.XX22.140503102847.X5H5,022PXX22.XX22.190719000411.Y1B8,022PXX22.XX22.160609231505.U5M2,022PXX22.XX22.191123162813.V2H5,022PXX22.XX22.180529161524.T4U2,022PXX22.XX22.120125171116.A2B9,022PXX22.XX22.190617194240.P3T9,022PXX22.XX22.161201181944.P2G8,022PXX22.XX22.130425112412.A5B1,022PXX22.XX22.140124161850.A6L7,022PXX22.XX22.170208143539.F3A3,022PXX22.XX22.161118203239.W9K5,022PXX22.XX22.120718162034.J5Y4,022PXX22.XX22.140411154046.J7D9,022PXX22.XX22.140124160050.E9Q1,022PXX22.XX22.160704110903.Y8G9,022PXX22.XX22.130831220242.Q9Z5,022PXX22.XX22.120507131522.S2E8,022PXX22.XX22.220812114826.B2M8,022PXX22.XX22.140124161355.B8C4,9999P2145.2145.180420114658.F9E9,020PXX20.XX20.200414235110.W7R2,020PXX20.XX20.221015055439.F7H1,020PXX20.XX20.110204182333.F1S5,020P5075856,020PXX20.XX20.120430134453.L2H5,020PXX20.XX20.120712215945.H8I8,020PXX20.XX20.130211121101.M5C4,020PXX20.XX20.130531161605.T5Q7,020PXX20.XX20.130724133127.B3E6,020PXX20.XX20.130208080001.P3P9,020PXX20.XX20.230416190007.K1I7,020PXX20.XX20.140626153026.D1J9,020PXX20.XX20.120731192102.U8F8,020PXX20.XX20.180628192601.H7G8",
        "nextdocidcount": "10",
        "scity": "Mumbai",
        "pcity": "Mumbai",
        "spincode": "400706",
        "amp": null,
        "cat_search_type": "Z",
        "area_docid_count_hotel": "",
        "area_last_docid_hotel": "",
        "adword_pos": [],
        "adword_snippet": [],
        "footer": 0,
        "adword_docids": "",
        "newadd": "Ad",
        "newaddcolor": "#ffffff",
        "newaddtextcolor": "#000000",
        "viewchange": [
            0
        ],
        "view_flag": null,
        "dsmap": 1,
        "vertical_banner": {},
        "srf": "11",
        "pharmacy_data": {},
        "not_rateable": 0,
        "brndname": "Vocational Course Training Centres",
        "mncatnm": "Vocational Course Training Centres",
        "comp_avg_starjd": "4.2|$|4233",
        "lng": "",
        "h1": "Top Vocational Course Training Centres in Mumbai",
        "nrin": " in ",
        "microdata": "",
        "ldJson": {
            "default": "{\"@context\": \"http://schema.org\",\"@type\": \"WebSite\",\"name\": \"Justdial\",\"url\": \"https://www.justdial.com/\"}",
            "rating": "{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Vocational Course Training Centres in Mumbai\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/navi-mumbai\\/l7\\/022pxx22.xx22.140524123935.v2l7\\/catalogue\\/the-art-hub-kharghar-navi-mumbai-drawing-classes-nnhu5.jpg\",\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Vocational-Course-Training-Centres\\/nct-11251622\",\"address\":{\"@type\":\"PostalAddress\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"999999\",\"addressCountry\":\"IN\"},\"aggregateRating\":{\"@type\":\"AggregateRating\",\"ratingValue\":\"4.2\",\"ratingCount\":\"4233\",\"bestRating\":\"5\"}}",
            "social": "[{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"Organization\",\"name\":\"justdial.com\",\"url\":\"https:\\/\\/www.justdial.com\\/\",\"logo\":\"https:\\/\\/akam.cdn.jdmagicbox.com\\/images\\/icontent\\/jdrwd\\/jdlogosvg.svg\",\"sameAs\":[\"https:\\/\\/www.facebook.com\\/JustDial\",\"https:\\/\\/plus.google.com\\/+justdial\",\"https:\\/\\/www.linkedin.com\\/company\\/justdial\",\"https:\\/\\/www.instagram.com\\/jd_justdial\",\"https:\\/\\/play.google.com\\/store\\/apps\\/details?id=com.justdial.search\",\"https:\\/\\/itunes.apple.com\\/app\\/jd-justdial\\/id624946027?uo=5\",\"https:\\/\\/www.youtube.com\\/user\\/justdialind\"]},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"S P Art Hub\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/navi-mumbai\\/l7\\/022pxx22.xx22.140524123935.v2l7\\/catalogue\\/the-art-hub-kharghar-navi-mumbai-drawing-classes-nnhu5.jpg\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Sector 12\",\"addresslocality\":\"Kharghar\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"410210\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/S-P-Art-Hub-Near-Sai-Baba-Mandir-Kharghar\\/022PXX22-XX22-140524123935-V2L7_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Kutchi ITI\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/h1\\/022pxx22.xx22.200415012633.k3h1\\/catalogue\\/kutchi-iti-mumbra-thane-accounting-training-institutes-vb9zgyn1ye.jpg?clr=#491d1d\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Mumbai Pune Road\",\"addresslocality\":\"Mumbra\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"400612\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Kutchi-ITI-Anand-Koliwada-Mumbra\\/022PXX22-XX22-200415012633-K3H1_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Revolution Fitness Academy\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/navi_mumbai\\/h9\\/022pxx22.xx22.150813191319.e8h9\\/catalogue\\/revolution-fitness-academy-kharghar-navi-mumbai-dietitians-s5d8.jpg?clr=#442233\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Sector - 07\",\"addresslocality\":\"Kharghar\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"410210\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Revolution-Fitness-Academy-Near-3-Star-Hotel-Kharghar\\/022PXX22-XX22-150813191319-E8H9_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Anandi Special School\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/04\\/022p8010204\\/catalogue\\/anandi-special-school-mumbai-sh3pcqz2gs.jpg?clr=#333333\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Shahaji Raje Marg\",\"addresslocality\":\"Vile Parle East\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"400057\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Anandi-Special-School-Near-Parle-G-Company-Vile-Parle-East\\/022P8010204_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"I-Tech Computer Education\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/palghar\\/v5\\/022pxx22.xx22.181007181027.r5v5\\/catalogue\\/i-tech-computer-education-nalasopara-west-palghar-computer-training-institutes-sxhi3mq4sn.jpg?clr=#123354\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Station Road\",\"addresslocality\":\"Nalasopara West\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"401203\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/I-Tech-Computer-Education-Opposite-Panchmukhi-Hanuman-Mandir-Nalasopara-West\\/022PXX22-XX22-181007181027-R5V5_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Om Creations Trust (Om Abode)\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/h1\\/022pxx22.xx22.230707173438.l3h1\\/catalogue\\/om-creations-trust-om-abode-mahalaxmi-mumbai-vocational-course-training-centres-a61dfuh89q.jpg?clr=#471f1f\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Dr E Moses Road\",\"addresslocality\":\"Mahalaxmi\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"400011\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Om-Creations-Trust-Om-Abode-Near-Famous-Studio-Mahalaxmi\\/022PXX22-XX22-230707173438-L3H1_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Addhyayan Institute\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/p2\\/022pxx22.xx22.190612093002.p1p2\\/catalogue\\/addhyayan-institute-kandivali-west-mumbai-computer-hardware-training-institutes-tucqbvwjk8.jpg?clr=#3a2c3a\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Charkop Market\",\"addresslocality\":\"Kandivali West\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"400067\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Addhyayan-Institute-Apna-Bazar-Kandivali-West\\/022PXX22-XX22-190612093002-P1P2_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Industrial Engineering Institute\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/thane\\/p4\\/022pxx22.xx22.000439459895.p8p4\\/catalogue\\/industrial-engineering-institute-thane-west-thane-vocational-course-training-centres-3clsovb.jpg?clr=#491d2c\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"R S Road\",\"addresslocality\":\"Thane West\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"400601\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Industrial-Engineering-Institute-Behind-Ashok-Cinema-Near-Datta-Mandir-and-Thane-College-Road-Thane-West\\/022PXX22-XX22-000439459895-P8P4_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Ishwari Nursing Institute\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/n4\\/022pxx22.xx22.220807130031.v6n4\\/catalogue\\/ishwari-academy-manda-thane-institutes-rk4tlo1wqm.jpg?clr=#4c1a1a\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Titwala-ambivali Road\",\"addresslocality\":\"Manda\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"421605\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Ishwari-Nursing-Institute-Opposite-Vidya-Mandir-School-Above-Titwala-Post-Office-Manda\\/022PXX22-XX22-220807130031-V6N4_BZDET\"},{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"LocalBusiness\",\"name\":\"Visvesvaraya Foundation\",\"image\":\"https:\\/\\/content.jdmagicbox.com\\/comp\\/udaipur-rajasthan\\/a7\\/9999px294.x294.140129101202.n7a7\\/catalogue\\/visvesvaraya-foundation-udaipur-city-udaipur-rajasthan-colleges-1001htsbgd.jpg?clr=#333333\",\"address\":{\"@type\":\"PostalAddress\",\"streetAddress\":\"Sector 4,Main Road\",\"addresslocality\":\"Udaipur City\",\"addressRegion\":\"Mumbai\",\"postalCode\":\"313001\",\"addressCountry\":\"IN\"},\"url\":\"https:\\/\\/www.justdial.com\\/Udaipur-Rajasthan\\/Visvesvaraya-Foundation-Opposite-Hansa-Palace-Udaipur-City\\/9999PX294-X294-140129101202-N7A7_BZDET\"}]",
            "listing": "{\"@context\": \"http://schema.org\",\"@type\": \"ItemList\",\n    \t\"itemListElement\" :[{\"@type\":\"ListItem\",\"position\":1,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/S-P-Art-Hub-Near-Sai-Baba-Mandir-Kharghar\\/022PXX22-XX22-140524123935-V2L7_BZDET\"},{\"@type\":\"ListItem\",\"position\":2,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Kutchi-ITI-Anand-Koliwada-Mumbra\\/022PXX22-XX22-200415012633-K3H1_BZDET\"},{\"@type\":\"ListItem\",\"position\":3,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Revolution-Fitness-Academy-Near-3-Star-Hotel-Kharghar\\/022PXX22-XX22-150813191319-E8H9_BZDET\"},{\"@type\":\"ListItem\",\"position\":4,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Anandi-Special-School-Near-Parle-G-Company-Vile-Parle-East\\/022P8010204_BZDET\"},{\"@type\":\"ListItem\",\"position\":5,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/I-Tech-Computer-Education-Opposite-Panchmukhi-Hanuman-Mandir-Nalasopara-West\\/022PXX22-XX22-181007181027-R5V5_BZDET\"},{\"@type\":\"ListItem\",\"position\":6,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Om-Creations-Trust-Om-Abode-Near-Famous-Studio-Mahalaxmi\\/022PXX22-XX22-230707173438-L3H1_BZDET\"},{\"@type\":\"ListItem\",\"position\":7,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Addhyayan-Institute-Apna-Bazar-Kandivali-West\\/022PXX22-XX22-190612093002-P1P2_BZDET\"},{\"@type\":\"ListItem\",\"position\":8,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Industrial-Engineering-Institute-Behind-Ashok-Cinema-Near-Datta-Mandir-and-Thane-College-Road-Thane-West\\/022PXX22-XX22-000439459895-P8P4_BZDET\"},{\"@type\":\"ListItem\",\"position\":9,\"url\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Ishwari-Nursing-Institute-Opposite-Vidya-Mandir-School-Above-Titwala-Post-Office-Manda\\/022PXX22-XX22-220807130031-V6N4_BZDET\"},{\"@type\":\"ListItem\",\"position\":10,\"url\":\"https:\\/\\/www.justdial.com\\/Udaipur-Rajasthan\\/Visvesvaraya-Foundation-Opposite-Hansa-Palace-Udaipur-City\\/9999PX294-X294-140129101202-N7A7_BZDET\"}]}",
            "brcrum": "{\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"BreadcrumbList\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"item\":{\"@id\":\"https:\\/\\/www.justdial.com\\/Mumbai\",\"name\":\"Mumbai\"}},{\"@type\":\"ListItem\",\"position\":2,\"item\":{\"@id\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Vocational-Course-Training-Centres\\/nct-11251622\",\"name\":\"Vocational Course Training Centres in Mumbai\"}},{\"@type\":\"ListItem\",\"position\":3,\"item\":{\"name\":\"137+ Listings\",\"@id\":\"https:\\/\\/www.justdial.com\\/Mumbai\\/Vocational-Course-Training-Centres\\/nct-11251622?#listings\"}}]}"
        },
        "ttlist": 137,
        "catessy": {},
        "og_tags": {
            "type": "company",
            "site_name": "Justdial",
            "title": "Top Vocational Course Training Centres in Mumbai - Best Vocational Course Training Centers near me - Justdial",
            "url": "https://www.justdial.com/Mumbai/Vocational-Course-Training-Centres/nct-11251622",
            "description": "137 Vocational Course Training Centres in Mumbai. Find ✓Tutorials, ✓Computer Training Institutes, ✓Institutes, ✓Digital Marketing Courses, ✓Institutes For Mobile Phone Servicing in Mumbai. Get Phone Numbers, Address, Reviews, Photos, Maps , FAQs for top Vocational Course Training Centres near me in Mumbai on Justdial.",
            "image": "https://akam.cdn.jdmagicbox.com/images/icontent/jd-logo_nw.png",
            "iosurl": "justdial://Mumbai/Vocational-Course-Training-Centres/nct-11251622",
            "androidurl": "android-app://com.justdial.search/http/t.justdial.com/Mumbai/Vocational-Course-Training-Centres/nct-11251622"
        },
        "canonic": "https://www.justdial.com/Mumbai/Vocational-Course-Training-Centres/nct-11251622",
        "chainoutlet": 0,
        "applink": [],
        "number_mask": 0,
        "bddisplayText1": "Get the list of best",
        "bddisplayText2": "Vocational Course Training Centres",
        "open_abd": 0,
        "enable_filter": 1,
        "dpa": "|EDU|",
        "bd_data": {
            "form_type": 0,
            "form_btn": "Send Enquiry",
            "form_heading": "Looking for Vocational Course Training Centres ?",
            "form_heading_top": "Get the List of Top",
            "form_heading_desc": "We'll send you contact details in seconds for free"
        },
        "abd_data": {},
        "bestDeal": "Fill this form to Send Enquiry for Vocational Course Training Centres",
        "bd_text": "Enquire Now",
        "bd_text_orig": "Send Enquiry for Vocational Course Training Centres!",
        "resultString": "in Mumbai",
        "bd_msgtype": "7",
        "bd_captiontype": "6",
        "aka": "",
        "newbddesign": "1",
        "calltext": "Call Now",
        "bdtextdata": "Send Enquiry",
        "bdtextdatali": "Send Enquiry",
        "paramsText": "&bd7=&magicname=bdgbp",
        "deal_pos": "7",
        "checkin": "2023-10-18",
        "checkout": "2023-10-19",
        "checkpos": "2",
        "dt_params": {
            "fromres": "1",
            "city": "Mumbai",
            "area": "",
            "pincode": "400706",
            "catid": "11251622",
            "national_catid": "11251622",
            "catname": " Vocational Course Training Centres"
        },
        "bd_params": {
            "bd": "1",
            "city": "Mumbai",
            "area": "",
            "pncdbd": "400706",
            "ncatid": "11251622",
            "search": "Vocational Course Training Centres",
            "case": "sms_email",
            "frmpg": "lspg"
        },
        "data_i_track": [],
        "other": 0,
        "noarea": null,
        "tabs": null,
        "stringdetail": "Based on,others have rated this,other have rated this,view all,call,message,share,direction,have rated this,your friend,be first among your friends to rate",
        "stringdetaileng": "Based on,others have rated this,other have rated this,view all,call,message,share,direction,have rated this,your friend,be first among your friends to rate",
        "rhs": 0,
        "error": {
            "status": 1,
            "fallbacksearch": "Vocational Course Training Centres",
            "rstatus": 200,
            "rurl": "",
            "inapp": 1
        },
        "phpRestime": 243.79272460938,
        "search_id": "6712f9995516403a0c41c0ad3083e615fa882e22379cfa9d555dc65a71c94640"
    })
}